export enum PaymentMethod {
    MandiriVA = 'mrivaesb',
    BcaVA = 'bcavaesb',
    BniVA = 'bnivaesb',
    BriVA = 'brivaesb',
    CimbVA = 'cimbvaesb',
    MybankVA = 'maybvaesb',
    PermataVA = 'prmtvaesb',
    ShopeePay = 'shopeepay',
    ShopeeXendit = 'shopeexen',
    Kredivo = 'kredivoesb',
    Qris = 'qrisesb',
    Ovo = 'ovo',
    GoPay = 'gopay',
    Dana = 'dana',
    LinkAja = 'linkaja',
    TaraPay = 'indepay',
    CreditDebit = 'creditcard',
}